/**
 * Stub payload-types — generated by `npm run generate:types` after `payload`
 * is installed. Replace with the auto-generated file in production.
 */
/* eslint-disable @typescript-eslint/no-empty-object-type */

export interface Config {
  collections: {}
  globals: {}
  user: User & { collection: 'users' }
}

export interface User {
  id: string
  email: string
  name?: string
  role?: 'admin' | 'partner' | 'state-partner' | 'pump-holder'
}

export {}
